// react-portfolio/src/app/components/CardAboutMe/CardAboutMe.tsx
import React, { CSSProperties } from "react";
import Image from "next/image";
import {
  Box,
  Card,
  Grid,
  Stack,
  Typography,
  useMediaQuery,
} from "@mui/material";
import styles from "./styles.module.scss";
import meBlue from "../../images/me_blue.png";

const CARD_FIELD_INFORMATIONS = [
  { title: "Nome", text: "Brendon Angelo" },
  { title: "Data de nascimento", text: "23/06/1999" },
  { title: "Área de atuação", text: "Front-end" },
  { title: "Formado em", text: "Ciência da Computação" },
];

export function CardAboutMe() {
  const matches = useMediaQuery("(max-width: 900px)");

  return (
    <div className={styles.card}>
      <div className={styles.reflectionEffect}>
        {Array.from(Array(3)).map((_, index) => {
          return (
            <div
              key={index}
              style={{
                height: "100%",
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <div
                className={styles.reflection1}
                style={{ marginLeft: index === 0 ? -100 : 100 }}
              ></div>
              <div
                className={styles.reflection2}
                style={{ marginLeft: 8 }}
              ></div>
              <div
                className={styles.reflection1}
                style={{ marginLeft: 20 }}
              ></div>
              <div
                className={styles.reflection2}
                style={{ marginLeft: 8 }}
              ></div>
              <div
                className={styles.reflection3}
                style={{ marginLeft: 200 }}
              ></div>
              <div
                className={styles.reflection3}
                style={{ marginLeft: 40 }}
              ></div>
              <div
                className={styles.reflection3}
                style={{ marginLeft: 40 }}
              ></div>
              <div
                className={styles.reflection4}
                style={{ marginLeft: 100 }}
              ></div>
              <div
                className={styles.reflection3}
                style={{ marginLeft: 5 }}
              ></div>
              <div
                className={styles.reflection4}
                style={{ marginLeft: 5 }}
              ></div>
            </div>
          );
        })}
      </div>
      <div className={styles.cardContent}>
        <Grid container columnSpacing={{ xs: matches ? 2 : 5 }}>
          <Grid item xs={matches ? 6 : 3.5}>
            <Card
              elevation={0}
              sx={{
                width: "100%",
                height: "fit-content",
                bgcolor: "secondary.main",
                border: "9px solid",
                borderColor: "secondary.main",
                borderRadius: 3,
                display: "flex",
                alignItems: "end",
              }}
            >
              <Image
                style={{ width: "100%", height: "auto" }}
                src={meBlue}
                alt="Me blue"
              />
            </Card>
          </Grid>
          <Grid item xs={matches ? 6 : 8.5}>
            <Grid container spacing={1}>
              {CARD_FIELD_INFORMATIONS.map((value, index) => {
                return (
                  <Grid key={index} item xs={matches ? 12 : 6}>
                    <Box
                      bgcolor={"secondary.main"}
                      padding={"8px 0 8px 8px"}
                      borderRadius={2}
                    >
                      <Stack textAlign={"start"}>
                        <Typography
                          lineHeight={1}
                          marginBottom={"5px"}
                          variant={matches ? "subtitle1" : "subtitle1"}
                        >
                          {value.title}
                        </Typography>
                        <Typography
                          lineHeight={1}
                          variant={matches ? "h6" : "h6"}
                        >
                          {value.text}
                        </Typography>
                      </Stack>
                    </Box>
                  </Grid>
                );
              })}
              <Grid item display={matches ? "none" : "block"}>
                {/* TODO COMPONENTIZAR A SESSÃO DE Descrição DO CARD */}
                <Box bgcolor={"secondary.main"} padding={1} borderRadius={2}>
                  <Stack textAlign={"start"}>
                    <Typography
                      lineHeight={1}
                      marginBottom={"5px"}
                      variant="subtitle1"
                    >
                      Descrição
                    </Typography>
                    <Typography lineHeight={"25px"} variant="h6">
                      Desde a infância, minha paixão por ilustrações e cores me
                      conduziu à criação digital. Hoje, como desenvolvedor
                      front-end, combino design com habilidades em{" "}
                      <span className={styles.javascriptColor}>JavaScript</span>
                      ,{" "}
                      <span className={styles.typescriptColor}>TypeScript</span>
                      ,<span className={styles.htmlColor}> HTML</span>,
                      <span className={styles.cssColor}> CSS</span>,{" "}
                      <span className={styles.sassColor}>SASS</span>,{" "}
                      <span className={styles.styledComponentColor}>
                        Styled Components
                      </span>
                      , <span className={styles.vueColor}>Vue.js</span> e React
                      para criar experiências web envolventes. Acredito na
                      colaboração entre design e código para cativar os
                      usuários, e estou em constante busca de aprimoramento.
                    </Typography>
                  </Stack>
                </Box>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
        <Grid container marginTop={1} display={matches ? "block" : "none"}>
          <Grid item xs={12}>
            <Box
              bgcolor={"secondary.main"}
              height={"100%"}
              paddingLeft={1}
              borderRadius={2}
            >
              <Stack alignItems={"start"}>
                <Typography variant="subtitle1">Descrição</Typography>
                <Typography
                  lineHeight={"25px"}
                  variant="h6"
                  textAlign={"initial"}
                >
                  Desde a infância, minha paixão por ilustrações e cores me
                  conduziu à criação digital. Hoje, como desenvolvedor
                  front-end, combino design com habilidades em{" "}
                  <span className={styles.javascriptColor}>JavaScript</span>,{" "}
                  <span className={styles.typescriptColor}>TypeScript</span>,
                  <span className={styles.htmlColor}> HTML</span>,
                  <span className={styles.cssColor}> CSS</span>,{" "}
                  <span className={styles.sassColor}>SASS</span>,{" "}
                  <span className={styles.styledComponentColor}>
                    Styled Components
                  </span>
                  , <span className={styles.vueColor}>Vue.js</span> e React para
                  criar experiências web envolventes. Acredito na colaboração
                  entre design e código para cativar os usuários, e estou em
                  constante busca de aprimoramento.
                </Typography>
              </Stack>
            </Box>
          </Grid>
        </Grid>
      </div>
    </div>
  );
}

// vue-portfolio/components/CardAboutMe.vue
<template>
  <div class="primary card">
    <div class="reflectionEffect">
      <div
        v-for="(_, index) in Array.from(Array(3))"
        :key="index"
        :style="{
          height: '100%',
          display: 'flex',
          justifyContent: 'center',
          alignItems: 'center',
        }"
      >
        <div
          class="reflection1"
          :style="{ marginLeft: index === 0 ? -100 : 100 }"
        ></div>
        <div class="reflection2" :style="{ marginLeft: '8px' }"></div>
        <div class="reflection1" :style="{ marginLeft: '20px' }"></div>
        <div class="reflection2" :style="{ marginLeft: '8px' }"></div>
        <div class="reflection3" :style="{ marginLeft: '200px' }"></div>
        <div class="reflection3" :style="{ marginLeft: '40px' }"></div>
        <div class="reflection3" :style="{ marginLeft: '40px' }"></div>
        <div class="reflection4" :style="{ marginLeft: '100px' }"></div>
        <div class="reflection3" :style="{ marginLeft: '5px' }"></div>
        <div class="reflection4" :style="{ marginLeft: '5px' }"></div>
      </div>
    </div>
    <div class="cardContent">
      <v-row class="ma-0 pa-0">
        <v-col class="pa-0" cols="auto">
          <v-card
            flat
            class="secondary pa-0 rounded-lg"
            style="border: 9px solid"
          >
            <v-img :src="image" :width="breakpoint900 ? '154' : '193'"></v-img>
          </v-card>
        </v-col>
        <v-col :class="`ma-0 pa-0  ${breakpoint900 ? 'ml-4' : 'ml-10'}`">
          <v-row class="pa-0 ma-0 mb-2">
            <v-col :class="`ma-0 pa-0 ${breakpoint900 ? 'mb-2' : 'mr-1'}`">
              <v-card
                class="secondary pl-2 py-2 rounded-lg"
                style="height: 100%"
                flat
              >
                <v-card-subtitle
                  class="pa-0 mb-1 primary--text font-size-subtitle"
                  style="line-height: 1"
                >
                  Nome
                </v-card-subtitle>
                <v-card-text
                  class="primary--text font-size-text pa-0"
                  style="line-height: 1"
                >
                  Brendon Angelo
                </v-card-text>
              </v-card>
            </v-col>
            <v-col :class="`ma-0 pa-0 ${!breakpoint900 ?? 'ml-1'}`">
              <v-card
                class="secondary pl-2 py-2 rounded-lg"
                style="height: 100%"
                flat
              >
                <v-card-subtitle
                  class="pa-0 mb-1 primary--text font-size-subtitle"
                  style="line-height: 1"
                >
                  Data de nascimento
                </v-card-subtitle>
                <v-card-text
                  class="primary--text font-size-text pa-0"
                  style="line-height: 1"
                >
                  23/06/1999
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>
          <v-row class="pa-0 ma-0 mb-2">
            <v-col :class="`ma-0 pa-0 ${breakpoint900 ? 'mb-2' : 'mr-1'}`">
              <v-card
                class="secondary pl-2 py-2 rounded-lg"
                style="height: 100%"
                flat
              >
                <v-card-subtitle
                  class="pa-0 mb-1 primary--text font-size-subtitle"
                  style="line-height: 1"
                >
                  Área de atuação
                </v-card-subtitle>
                <v-card-text
                  class="primary--text font-size-text pa-0"
                  style="line-height: 1"
                >
                  Front-end
                </v-card-text>
              </v-card>
            </v-col>
            <v-col :class="`ma-0 pa-0 ${!breakpoint900 ?? 'ml-1'}`">
              <v-card
                class="secondary pl-2 py-2 rounded-lg"
                style="height: 100%"
                flat
              >
                <v-card-subtitle
                  class="pa-0 mb-1 primary--text font-size-subtitle"
                  style="line-height: 1"
                >
                  Formado em
                </v-card-subtitle>
                <v-card-text
                  class="primary--text font-size-text pa-0"
                  style="line-height: 1"
                >
                  Ciência da Computação
                </v-card-text>
              </v-card>
            </v-col>
          </v-row>
          <v-row v-if="!breakpoint900" class="pa-0 ma-0">
            <v-card
              class="secondary pl-2 py-2 rounded-lg"
              style="height: 100%; width: 100%"
              flat
            >
              <v-card-subtitle
                class="pa-0 mb-1 primary--text font-size-subtitle"
                style="line-height: 1"
              >
                Descrição
              </v-card-subtitle>
              <v-card-text
                class="primary--text font-size-text pa-0"
                style="line-height: 25px"
              >
                Desde a infância, minha paixão por ilustrações e cores me
                conduziu à criação digital. Hoje, como desenvolvedor front-end,
                combino design com habilidades em
                <span class="javascriptColor">JavaScript</span>,
                <span class="typescriptColor">TypeScript</span>,
                <span class="htmlColor">HTML</span>,
                <span class="cssColor"> CSS</span>,
                <span class="sassColor">SASS</span>,
                <span class="styledComponentColor">Styled Components</span>,
                Vue.js e <span class="reactColor">React</span> para criar
                experiências web envolventes. Acredito na colaboração entre
                design e código para cativar os usuários, e estou em constante
                busca de aprimoramento.
              </v-card-text>
            </v-card>
          </v-row>
        </v-col>
      </v-row>
      <v-row v-if="breakpoint900" class="ma-0 pa-0">
        <v-card
          class="secondary pl-2 py-2 rounded-lg"
          style="height: 100%; width: 100%"
          flat
        >
          <v-card-subtitle
            class="pa-0 mb-1 primary--text font-size-subtitle"
            style="line-height: 1"
          >
            Descrição
          </v-card-subtitle>
          <v-card-text
            class="primary--text font-size-text pa-0"
            style="line-height: 25px"
          >
            Desde a infância, minha paixão por ilustrações e cores me conduziu à
            criação digital. Hoje, como desenvolvedor front-end, combino design
            com habilidades em
            <span class="javascriptColor">JavaScript</span>,
            <span class="typescriptColor">TypeScript</span>,
            <span class="htmlColor">HTML</span>,
            <span class="cssColor"> CSS</span>,
            <span class="sassColor">SASS</span>,
            <span class="styledComponentColor">Styled Components</span>, Vue.js
            e <span class="reactColor">React</span> para criar experiências web
            envolventes. Acredito na colaboração entre design e código para
            cativar os usuários, e estou em constante busca de aprimoramento.
          </v-card-text>
        </v-card>
      </v-row>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";
import image from "@/images/me_green.png";

export default Vue.extend({
  data() {
    return {
      image,
    };
  },
  computed: {
    breakpoint900(): boolean {
      return this.$vuetify.breakpoint.width <= 900;
    },
  },
});
</script>

<style lang="scss" scoped>
@mixin reflections-default-properties {
  height: 140%;
  background-color: white;
  opacity: 0.9;
  rotate: 35deg;
}

.htmlColor {
  color: #e44d26;
}
.javascriptColor {
  color: #f7df1e;
}
.reactColor {
  color: #00dbfb;
}
.typescriptColor,
.cssColor {
  color: #046fe5;
}
.styledComponentColor,
.sassColor {
  color: #cf649a;
}

.font-size-subtitle {
  font-size: 16px;
}
.font-size-text {
  font-size: 20px;
}

.card {
  width: 900px;
  height: auto;
  margin-top: 50px;
  z-index: 0;
  position: relative;
  border-radius: 15px;
  overflow: hidden;
  .cardContent {
    width: 100%;
    height: 100%;
    padding: 40px;
  }
  .reflectionEffect {
    z-index: -1;
    width: 180%;
    height: 100%;
    display: flex;
    align-items: center;
    position: absolute;
    opacity: 0.6;
    animation: moveRightLeft 10s ease-in-out infinite;
    .reflection1 {
      width: 15px;
      @include reflections-default-properties();
    }
    .reflection2 {
      width: 10px;
      @include reflections-default-properties();
    }
    .reflection3 {
      width: 10px;
      @include reflections-default-properties();
    }
    .reflection4 {
      width: 5px;
      @include reflections-default-properties();
    }
  }
}

@keyframes moveRightLeft {
  0%,
  100% {
    left: -90%;
  }
  20% {
    left: -90%;
  }
  50% {
    left: 20%;
  }
  70% {
    left: 20%;
  }
}

@media screen and (max-width: 900px) {
  .card {
    width: 400px;
    margin-top: 30px;
    .cardContent {
      padding: 20px;
    }
    .reflectionEffect {
      animation: moveRightLeft2 10s ease-in-out infinite;
    }
  }
  @keyframes moveRightLeft2 {
    0%,
    100% {
      left: -330%;
    }
    20% {
      left: -330%;
    }
    50% {
      left: 20%;
    }
    70% {
      left: 20%;
    }
  }
  @media screen and (max-device-width: 399px) {
    .card {
      width: 100%;
    }
  }
}
</style>
